// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqVZhA4j6DpdNyZ2TQYDN-8axPeF3JzU',
    appId: '1:36769619694:android:55638dde3b88e75f611dff',
    messagingSenderId: '36769619694',
    projectId: 'picklist-by',
    storageBucket: 'picklist-by.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh-GYU_eq6AUqoG_Z5FYPRKxRFjxqh-TY',
    appId: '1:36769619694:ios:f47ec362d84d1265611dff',
    messagingSenderId: '36769619694',
    projectId: 'picklist-by',
    storageBucket: 'picklist-by.firebasestorage.app',
    iosClientId:
        '36769619694-o3l9s3j8640erndiqhh5f3h3becaq44g.apps.googleusercontent.com',
    iosBundleId: 'com.pickllist.pickllist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKMUhK_2uGwCQarYVd695qOTyDv0jiiVk',
    appId: '1:36769619694:web:5e8877fb8a6490d3611dff',
    messagingSenderId: '36769619694',
    projectId: 'picklist-by',
    authDomain: 'picklist-by.firebaseapp.com',
    storageBucket: 'picklist-by.firebasestorage.app',
    measurementId: 'G-NCKRFKFPYY',
  );
}
